### ISSUE TITLE
English Support

### ISSUE THREAD

**Issue by aksh1618** [zhouhua/remark-media-card#2]
Hey, I came here form https://github.com/zhouhua/obsidian-markdown-media-card, really neat plugin! It would be great if there was a setting to choose English as the language for labels in the card! Are there any plans to add such a support?

**Comment by zhouhua** [comment]
Thank you for liking my work.

When I initially designed this feature, I did consider English support (including an English version of the documentation as proof 😃). However, the decision not to implement multi-language support ultimately came down to the following two reasons:

1. I was entirely uncertain whether anyone besides myself would use this plugin, and I didn't promote it. So, from that perspective, I felt that adding features beyond my own use would be a bit self-indulgent.

2. Even without specifically supporting multiple languages, there are workarounds to satisfy the vast majority of English use cases. Take book cards as an example: the involved YAML fields such as ﻿url, ﻿title, ﻿cover, and ﻿introduction inherently do not have multilingual issues. To avoid complications, you just need to bypass fields like ﻿author, ﻿publishDate, and ﻿rating (even capitalizing the first letter is sufficient). For instance, to specify the author of a book, as long as you don't use ﻿author, there won't be any language barriers. You could use ﻿Author, ﻿AUTHOR, ﻿writer, or other variations.

**Comment by aksh1618** [comment]
Ohh I didn't realize that, awesome! Maybe I should have read till the end of the README, my bad :sweat_smile: Just tried capitalizing and it does work perfectly, thanks!
